export const CATEGORY_MAP_REDUCERS_TYPES = {
    SET_CATEGORY_MAP_START: 'category/SET_CATEGORY_MAP_START',
    SET_CATEGORY_MAP_SUCCESS: 'category/SET_CATEGORY_MAP_SUCCESS',
    SET_CATEGORY_MAP_FAILED: 'category/SET_CATEGORY_MAP_FAILED',
}